# Generated by Django 4.2.16 on 2024-11-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FanBoard_MMORPG', '0003_remove_article_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('tank', 'Танки'), ('heal', 'Хилы'), ('dd', 'ДД'), ('buyers', 'Торговцы'), ('gildemaster', 'Гилдмастеры'), ('quest', 'Квестгиверы'), ('smith', 'Кузнецы'), ('tanner', 'Кожевники'), ('potion', 'Зельевары'), ('spellmaster', 'Мастера заклинаний')], default='Tanks', max_length=25),
        ),
    ]
