# Generated by Django 4.2.16 on 2024-11-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FanBoard_MMORPG', '0004_alter_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(default='Tanks', to='FanBoard_MMORPG.category'),
        ),
    ]
