# Generated by Django 4.2.16 on 2024-11-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FanBoard_MMORPG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upload',
            field=models.FileField(default='null', upload_to='uploads/'),
        ),
    ]
